version: '2'
services:
    # mona is an image of litecoin node which used as base image for monad and
    # monactl. The environment variables default values determined on stage of
    # container start within starting script.
    monad:
      image: monad
      container_name: monad
      build:
        context: monad/
      volumes:
        - shared:/rpc
        - litecoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
        - MINING_ADDRESS
      entrypoint: ["./start-monad.sh"]

    lnd:
      image: lnd
      container_name: lnd_mona
      build:
        context: ../
        dockerfile: docker/lnd/Dockerfile
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
        - shared:/rpc
        - lnd_mona:/root/.lnd
      entrypoint: ["./start-lnd.sh"]
      links:
        - "monad:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # monactl and lnd containers.
  shared:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during monad container recreation.
  litecoin:
    driver: local

  # lnd volume is used for persisting lnd application data and chain state
  # during container lifecycle.
  lnd_mona:
    driver: local
